batch_type: numel
batch_bins: 16000000
accum_grad: 4
max_epoch: 70

encoder: ds2
encoder_conf:
    rnn_type: gru
    rnn_hidden_size: 800
    bidirectional: False

decoder: identity
decoder_conf:
    hello: world

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

seed: 2022
log_interval: 400   
num_att_plot: 0     
num_workers: 8      
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

use_amp: true      
cudnn_deterministic: false  
cudnn_benchmark: false      

optim: adam
optim_conf:
    lr: 0.002
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

specaug: none

