batch_type: numel
batch_bins: 16000000
accum_grad: 4
max_epoch: 70

preprocessor: noise_split
preprocessor_conf:
    train_noise_scp: train_noise.scp
    nontrain_noise_scp: dev_noise.scp
noise_apply_prob: 0.9
noise_db_range: "0_25"
freeze_param: [
"frontend.upstream"
]
frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wavlm_local    # Note: If the upstream is changed, please change the input_size in the preencoder.
        upstream_ckpt: /ssdhome/lgx521/pkg/pre-training/pre_trained_model/wavlm/WavLM-Large.pt
    download_dir: ./hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80
encoder: conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 1024
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    rel_pos_type: latest
    pos_enc_layer_type: rel_pos
    selfattention_layer_type: rel_selfattn
    activation_type: swish
    use_cnn_module: true
    cnn_module_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false

seed: 2022
log_interval: 400   
num_att_plot: 0     
num_workers: 8
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 5

use_amp: true      
cudnn_deterministic: false  
cudnn_benchmark: false      

optim: adam
optim_conf:
    lr: 0.002
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

specaug: none
