batch_type: numel
batch_bins: 16000000
accum_grad: 4
max_epoch: 70

preprocessor: noise_split
preprocessor_conf:
    train_noise_scp: train_noise.scp
    nontrain_noise_scp: dev_noise.scp
noise_apply_prob: 0.9
noise_db_range: "0_25"


decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

seed: 2022
log_interval: 400   
num_att_plot: 0     
num_workers: 8
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 5

use_amp: true      
cudnn_deterministic: false  
cudnn_benchmark: false      

optim: adam
optim_conf:
    lr: 0.002
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000

specaug: none
