# Trained with Ampere A6000(48GB) x 2 GPUs. It takes about 10 days.
batch_type: numel
# batch_bins: 40000000
batch_bins: 4000000
num_workers: 16
accum_grad: 4
max_epoch: 50
seed: 2022
patience: 5
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 5
unused_parameters: true

preprocessor: noise_dev
preprocessor_conf:
    noise_map_scp: wav_noise_map.scp
noise_apply_prob: 0.875
noise_scp: noise.scp
noise_db_range: "0_25"

freeze_param: [
"frontend.upstream"
]
frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wavlm_local    # Note: If the upstream is changed, please change the input_size in the preencoder.
        upstream_ckpt: /ssdhome/lgx521/pkg/pre-training/pre_trained_model/wavlm/WavLM-Large.pt
    download_dir: ./hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 1104  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80

encoder: conformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d2
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module:  true
    cnn_module_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1
model: utt_nat_cat_frame
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false   # Note: "False" means during collect stats (stage 10), generating dummy stats files rather than extract_feats by forward frontend.
    frame_noise_vector_scp: "test_npy.scp"
    noise_vector_dim: 40


optim: adam
optim_conf:
    lr: 0.0008
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 50000

specaug: none
